// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBokGrnFxeNshb4rtPnKqHQ1GaRrZ-uIgE',
    appId: '1:826312714355:web:0154952fe267524f266206',
    messagingSenderId: '826312714355',
    projectId: 'flutter-fire-base-9083a',
    authDomain: 'flutter-fire-base-9083a.firebaseapp.com',
    storageBucket: 'flutter-fire-base-9083a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_80XWCCzSFwotAJZIoipFLXVSGiBhHfM',
    appId: '1:826312714355:android:ae3d44d1e2f4b0ee266206',
    messagingSenderId: '826312714355',
    projectId: 'flutter-fire-base-9083a',
    storageBucket: 'flutter-fire-base-9083a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtRyOPPKXMnR_wn8wLImUF_NXMtl7rKLI',
    appId: '1:826312714355:ios:8d807fc7a9befb91266206',
    messagingSenderId: '826312714355',
    projectId: 'flutter-fire-base-9083a',
    storageBucket: 'flutter-fire-base-9083a.appspot.com',
    iosClientId: '826312714355-d6fnqc0tr94cdv4uo4s0ke92f94gefip.apps.googleusercontent.com',
    iosBundleId: 'com.example.fDeliVery',
  );
}
